Add deletenc option

diff --git a/bin/bandbuilder_wizard b/bin/bandbuilder_wizard
--- a/bin/bandbuilder_wizard
+++ b/bin/bandbuilder_wizard
@@ -20,6 +20,8 @@ print_help() {
   echo "-m  Specify if a merged .nc file should be generated (enter T for True) [default: F]"
   echo "-cp Specify the path to cptraj (only needed if -m T) [default: cpptraj]"
   echo "-g  Growth method for generating the initial band [default: F]"
+  echo "-bi  Turn on bidirectional Growth method for generating the initial band [default: F]"
+  echo "-d  Delete .nc files generated during Growth method simulation [default: F]"
   echo "-s  Specify the path to sander or pmemd (only needed if -g T) [default: sander]"
   echo "-i  Name of the input file for the dynamics simulations  (only needed if -g T) [growth.mdin: F]"
   echo "----------------------------------------------------------------------------------------------------------------------"
@@ -39,11 +41,12 @@ SANDER=sander                                         #Should be replaced by the
 MDIN=growth.mdin                                      #Sander input
 GROWTH=F
 BIDIRECTIONAL=F
+DELETENC=F
 MERGE=F
 #--------
 
 # Parse command line arguments
-while getopts "hb:m:cp:g:bi:s:i:" opt; do
+while getopts "hb:m:cp:g:bi:d:s:i:" opt; do
   case ${opt} in
     h ) print_help
         exit 0
@@ -56,7 +59,9 @@ while getopts "hb:m:cp:g:bi:s:i:" opt; do
       ;;
     g ) GROWTH=$OPTARG
       ;;
-    g ) BIDIRECTIONAL=$OPTARG
+    bi ) BIDIRECTIONAL=$OPTARG
+      ;;
+    d ) DELETENC=$OPTARG
       ;;
     s ) SANDER=$OPTARG
       ;;
@@ -216,6 +221,11 @@ if [ "$GROWTH" == "T" ]; then
     echo "Error: BIDIRECTIONAL must be either 'T' or 'F'."
     exit 1
   fi
+  # Check if DELETENC is either 'T' or 'F'
+  if ! echo "$DELETENC" | grep -E -q '^[TF]$'; then
+    echo "Error: DELETENC must be either 'T' or 'F'."
+    exit 1
+  fi
 fi
 
 # In CPPTRAJ will be used, check that the path is correctly set
@@ -348,6 +358,9 @@ else
                -x ${NAME}_${k}.nc \
                -ref ${NAME}_initial_${k}.rst7
   done
+fi
+if [ "$DELETENC" == "T" ]; then
+  rm *.nc
 fi
 mkdir -p ../STEP-0-INITIAL
 if [ "$MERGE" == "T" ]; then
