improve wizard

diff --git a/bin/feneb_wizard b/bin/feneb_wizard
--- a/bin/feneb_wizard
+++ b/bin/feneb_wizard
@@ -16,15 +16,15 @@ NIMAGES=15                                            #Number of images
 NCPU=1                                                #Number of available CPU threads
 STARTSTEP=1                                           #Starting optimization step.
 MAXSTEPS=10                                           #Maximum optimization steps to be performed.
-DELETENC=1                                            #Delete .nc files after processing ("1" for True)
-GREPEVOLUTION=1                                       #Append band and maxgrad evolution ("1" for True)
+DELETENC=T                                            #Delete .nc files after processing ("1" for True)
+GREPEVOLUTION=T                                       #Append band and maxgrad evolution ("1" for True)
 NAPTIME=10                                            #How long should the script sleep
 NAPUNITS=s                                            #In which units (h,s,m)
 #-------------------------------------------------------------------------------------------------------------
 #NOTES:
 #[1] The directory where this script is executed must contain an "inputs" directory, with $TOPOLOGY, $MDIN,
 # feneb.in, feneb.extrema1 and feneb.extrema2 files (note it is assumed "rextrema" is set to True in
-# feneb.ini) as well as a directory called called $STARTSTEP-1, with the coordinates corresponding to
+# feneb.in) as well as a directory called called $STARTSTEP-1, with the coordinates corresponding to
 # the previous band ("0", in case $STARTSTEP=1).
 # This directory is automatically generated, but if this is the first step, must be manually created
 #[2] Before executing the feneb code, this script checks whether the $NIMAGES MD runs have finished or not
@@ -52,13 +52,12 @@ print_help() {
   echo "-d  maximum optimization steps to be performed [10]"
   echo "-g  delete .nc files after processing (1 for True) [1]"
   echo "-a  append band and maxgrad evolution (1 for True) [1]"
-  echo "-r  use fenen.extrema files (1 for True) [1]"
   echo "-u  how long should the script sleep [10]"
   echo "-v  in which units [s]"
 }
 
 # Parse command line arguments
-while getopts "hs:f:m:c:t:n:i:x:d:g:a:r:u:" opt; do
+while getopts "hs:f:m:c:t:n:i:x:d:g:a:u:" opt; do
   case ${opt} in
     h ) print_help
         exit 0
@@ -115,13 +114,6 @@ while getopts "hs:f:m:c:t:n:i:x:d:g:a:r:u:" opt; do
           exit 1
         fi
       ;;
-    r ) REXTREMA=$OPTARG
-        if ! [[ "$REXTREMA" =~ ^[0-9]+$ ]]
-        then
-          echo "Error: -r option requires a numeric argument."
-          exit 1
-        fi
-      ;;
     u ) NAPTIME=$OPTARG
         if ! [[ "$NAPTIME" =~ ^[0-9]+$ ]]
         then
@@ -160,29 +152,8 @@ if ! echo "$NAPUNITS" | grep -E -q '^[smd]$'; then
   exit 1
 fi
 
-# Check if DELETENC, REXTREMA, and GREPEVOLUTION are either '1' or '0'
-for var in "DELETENC" "REXTREMA" "GREPEVOLUTION"; do
-  if ! echo "${!var}" | grep -E -q '^[01]$'; then
-    echo "Error: $var must be either '1' or '0'."
-    exit 1
-  fi
-done
-
 # Check if NCPU is a number
 is_num "$NCPU" "NCPU"
-
-# Check NCPU against NIMAGES or NIMAGES-2 based on REXTREMA value
-if [ "$REXTREMA" -eq 1 ]; then
-  if [ "$NCPU" -gt "$(($NIMAGES - 2))" ]; then
-    echo "NCPU cannot be larger than NIMAGES-2 when REXTREMA=1. Setting NCPU to NIMAGES-2."
-    NCPU="$(($NIMAGES - 2))"
-  fi
-elif [ "$REXTREMA" -eq 0 ]; then
-  if [ "$NCPU" -gt "$NIMAGES" ]; then
-    echo "NCPU cannot be larger than NIMAGES when REXTREMA=0. Setting NCPU to NIMAGES."
-    NCPU="$NIMAGES"
-  fi
-fi
 
 # Make sure NCPU is still a positive integer after any adjustments
 if [ "$NCPU" -le 0 ]; then
@@ -198,12 +169,7 @@ if [ ! -d "inputs" ]; then
 fi
 
 # Check if required files exist
-if [ $REXTREMA == "1" ] #In this case, extra files are needed
-then
-  REQUIRED_FILES=("prod.mdin" "feneb.in" "feneb.extrema1" "feneb.extrema2" "$TOPOLOGY")
-else
-  REQUIRED_FILES=("prod.mdin" "feneb.in" "$TOPOLOGY")
-fi
+REQUIRED_FILES=("feneb.in" "prod.mdin" "$TOPOLOGY")
 for file in "${REQUIRED_FILES[@]}"; do
     if [ ! -f "inputs/$file" ]; then
         echo "Error: Required file $file not found in inputs directory."
@@ -211,16 +177,72 @@ for file in "${REQUIRED_FILES[@]}"; do
     fi
 done
 
-for ((i=STARTSTEP; i<=MAXSTEPS; i++)); # Optimization loop
+# Check if the extremes are fixed by inspecting the feneb.in file
+if  grep -s -q -F "rextrema" "inputs/feneb.in";
+then
+  REXTREMA=$(grep rextrema inputs/feneb.in|awk '{print $2}')
+  # Check if REXTREMA is T or F
+  REXTREMA=$(echo "${REXTREMA}" | tr -d '[:space:]')
+  if ! echo "${REXTREMA}" | grep -E -q '^[TF]$'; then
+    echo "Error: $REXTREMA must be either 'T' or 'F'."
+    exit 1
+  fi
+
+else
+  REXTREMA=F
+fi
+
+if [ "$REXTREMA" == "T" ]; then
+  REQUIRED_FILES=("feneb.extrema1" "feneb.extrema2")
+  for file in "${REQUIRED_FILES[@]}"; do
+    if [ ! -f "inputs/$file" ]; then
+        echo "Error: REXTREMA=T in feneb.in but required file $file not found in inputs directory."
+        exit 1
+    fi
+   done
+fi
+# Determine NIMAGES by inspecting the feneb.in file
+if  grep -s -q -F "nrep" "inputs/feneb.in";
+then
+  NIMAGES=$(grep nrep inputs/feneb.in|awk '{print $2}')
+  # Check if NIMAGES is a number
+  is_num "$NIMAGES" "NIMAGES"
+else
+  echo "Error: The number of images not found in feneb.in (nrep)"
+  exit 1
+fi
+
+# Check if DELETENC, REXTREMA, and GREPEVOLUTION are either 'T' or 'F'
+for var in "DELETENC" "GREPEVOLUTION"; do
+  if ! echo "${!var}" | grep -E -q '^[TF]$'; then
+    echo "Error: $var must be either 'T' or 'F'."
+    exit 1
+  fi
+done
+
+# Check NCPU against NIMAGES or NIMAGES-2 based on REXTREMA value
+if [ "$REXTREMA" == "T" ]; then
+  if [ "$NCPU" -gt "$(($NIMAGES - 2))" ]; then
+    echo "NCPU cannot be larger than NIMAGES-2 when REXTREMA=1. Setting NCPU to NIMAGES-2."
+    NCPU="$(($NIMAGES - 2))"
+  fi
+elif [ "$REXTREMA" == "F" ]; then
+  if [ "$NCPU" -gt "$NIMAGES" ]; then
+    echo "NCPU cannot be larger than NIMAGES when REXTREMA=0. Setting NCPU to NIMAGES."
+    NCPU="$NIMAGES"
+  fi
+fi
+
+for ((step=STARTSTEP; step<=MAXSTEPS; step++)); # Optimization loop
 do
-        mkdir -p $i #Creates a directory for the $i-th optimization step
-        cd $i
+        mkdir -p $step #Creates a directory for the $i-th optimization step
+        cd $step
         #Copy input files and topology
         cp ../inputs/$MDIN .
         cp ../inputs/feneb.* .
         cp ../inputs/$TOPOLOGY  .
         #From now on we need to know if the extremes are fixed or not
-        if [ $REXTREMA == "1" ] #If the extremes of the band are fixed
+        if [ $REXTREMA == "T" ] #If the extremes of the band are fixed
         then
           STARTREP=2
           ENDREP=$((NIMAGES-1))
@@ -229,8 +251,8 @@ do
           ENDREP=$((NIMAGES))
         fi
         #Copy coordinates from previous optimization step ("0" if this is the first optimization step)
-        j=$(($i-1|bc)) #Previous optimization step
-        if [ $i == "1" ] #If this is the first optimization step, copy _r_ files to _f_
+        j=$(($step-1|bc)) #Previous optimization step
+        if [ $step == "1" ] #If this is the first optimization step, copy _r_ files to _f_
           then
           for ((k=STARTREP; k<=ENDREP; k++));
           do
@@ -248,7 +270,7 @@ do
 	#If M < N, then we need to split the MD runs in packages. A smarter option would be
 	#to implement the FENEB code in the MPI version of sander, but I don't want to patch
 	#the AMBER code.
-  if [ $REXTREMA == "1" ] #If the extremes of the band are fixed
+  if [ $REXTREMA == "T" ] #If the extremes of the band are fixed
   then
     NRUNS=$((NIMAGES-2))
   else
@@ -256,14 +278,55 @@ do
   fi
 
 	NPACKAGES=$((NRUNS/NCPU))
+  NREMAINING=$((NRUNS-NPACKAGES*NCPU))
+
+  if [ "$step" == "$STARTSTEP" ];then
+  echo "----------------------------------------------------------------------"
+  echo "                             FENEB WIZARD                             "
+  echo "----------------------------------------------------------------------"
+  echo "This is a bash script that automatices the run of a FENEB calculation."
+  echo " "
+  echo "Usage: feneb_wizard [OPTIONS]"
+  echo "Options: [default]"
+  echo "-s  path to sander [sander]"
+  echo "-f  path to feneb [feneb]"
+  echo "-c  numer of cpu threads available [1]"
+  echo "-m  sander input [prod.mdin]"
+  echo "-t  topology file [SYSTEM.prmtop]"
+  echo "-n  prefix for all coordinates files [SYSTEM]"
+  echo "-x  starting optimization step [1]"
+  echo "-d  maximum optimization steps to be performed [10]"
+  echo "-g  delete .nc files after processing (T for True) [T]"
+  echo "-a  append band and maxgrad evolution (T for True) [T]"
+  echo "-u  how long should the script sleep [10]"
+  echo "-v  in which units [s]"
+  echo " "
+  fi
+  echo "----------------------------------------------------------------------"
+  echo "                    STARTING THE FENEB SIMULATION                     "
+  echo "----------------------------------------------------------------------"
+  echo " "
+  echo "The simulation will be parallelized according to the required number of"
+  echo "MD simulations to be performed and the number of cpu threads available."
+  echo " "
+  if [ $NREMAINING == '0' ]; then
+    echo  "The $NRUNS  MD simulations will be run in $NPACKAGES packages of $NCPU each."
+  else
+    echo  "The $NRUNS  MD simulations will be run in $NPACKAGES packages of $NCPU each"
+    echo  "and an extra one with $NREMAINING simulations"
+  fi
+  echo "----------------------------------------------------------------------"
+  echo " STEP: $step  "
+  echo "----------------------------------------------------------------------"
 	#Note NPACKAGES is rounded down. For example, if M=8 and NRUNS=23 (25 images with fixed extremes),
   #NPACKAGES will be equal to 2. So, after running 2*8=16 MD runs, we still need to run the remaining
 	#NRUNS-(NPACKAGES*M) runs.
 
   FROM=$((STARTREP))
-	UPTO=$((FROM+NCPU))
+	UPTO=$((FROM+NCPU-1))
         for ((i=1; i<=NPACKAGES; i++)); # Start running each PACKAGE of M MD simulations
         do
+          echo "Running package $i (range from $FROM to $UPTO)"
           for ((k=FROM;k<UPTO;k++)); # Start running M-1 MD
           do
             $SANDER -O -i prod.mdin \
@@ -296,19 +359,19 @@ do
                 echo "image number $l has not finished"
               fi
             done
-            if [ $count == $NCPU ]
+            if [ "$count" == "$NCPU" ]
             then
               echo "all Images of package $i have finished"
             else
               echo "taking a" $NAPTIME $NAPUNITS " long nap..."
-	            echo "..."
               sleep $NAPTIME$NAPUNITS
             fi
           done
           FROM=$((k+1))
-          UPTO=$((FROM+NCPU))
-	done
-	#Runs remaining MD simulations (if any)
+          UPTO=$((FROM+NCPU-1))
+        done #packages
+	      #Runs remaining MD simulations (if any)
+        if [ $NREMAINING != '0' ]; then
         UPTO=$((ENDREP))
         for ((k=FROM; k<UPTO; k++)); # Starts in k+1 image, according to last FROM update
         do
@@ -328,8 +391,7 @@ do
                    -r ${NAME}_f_${k}.rst7 \
                    -x ${NAME}_f_${k}.nc \
                    -ref ${NAME}_r_${k}.rst7
-	#Checks that all remaining Images have finished
-	NREMAINING=$((ENDREP-1-FROM))
+	      #Checks that all remaining Images have finished
         count=0
         while [ $count -lt $NREMAINING ];
         do
@@ -348,32 +410,31 @@ do
             echo "all remaining Images have finished"
           else
             echo "taking a" $NAPTIME $UNITS " long nap..."
-            echo "..."
             sleep $NAPTIME$UNITS
           fi
         done
-
+        fi
 	#Run feneb
         echo "Running feneb optimization"
         $FENEB
 
-	if [ $DELETENC == "1" ] #Delete .nc files
+	if [ $DELETENC == "T" ] #Delete .nc files
         then
           rm *.nc
   fi
 
 	for ((k=STARTREP; k<=ENDREP; k++)); #Copy files for next movement
         do
-          cp ${NAME}_o_${k}.rst7 _r_${k}.rst7
-        done
+          cp ${NAME}_o_${k}.rst7 ${NAME}_r_${k}.rst7
+  done
 
-        if [ $GREPEVOLUTION == "1" ] #Copy optimization information to .dat files
-        then
-          GRADPERP=$(grep "Band max force:" feneb.out|awk '{print $4}')
-          cat profile.dat >> ../bandevolution.dat
-          echo " " >> ../bandevolution.dat
-          echo $i $GRADPERP >> ../maxgradevolution.dat
-        fi
-        echo "Step: "$i " finished"
-        cd ..
+  if [ $GREPEVOLUTION == "T" ] #Copy optimization information to .dat files
+  then
+    GRADPERP=$(grep "Band max force:" feneb.out|awk '{print $4}')
+    cat profile.dat >> ../bandevolution.dat
+    echo " " >> ../bandevolution.dat
+    echo $step $GRADPERP >> ../maxgradevolution.dat
+  fi
+    echo "Step: "$step " finished"
+    cd ..
 done
