feopt wizard

diff --git a/bin/feopt_wizard b/bin/feopt_wizard
--- a/bin/feopt_wizard
+++ b/bin/feopt_wizard
@@ -1,48 +1,38 @@
 #!/bin/bash
 #-------------------------------------------------------------------------------------------------------------
-# This is a tool to run a FENEB optimization starting with an initial band of NIMAGES images, and running them
-# in parallel using NCPU cpu threads.
+# This is a tool to run a Free Energy optimization using a single CPU thread
 #
 # Written by Jonathan A. Semelak
 #-------------------------------------------------------------------------------------------------------------
 SANDER=sander                                         #Should be replaced by the corresponding path to sander
 FENEB=feneb                                           #Should be replaced by the corresponding path to feneb
 MDIN=prod.mdin                                        #Sander input
-NIMAGES=15                                            #Number of images
-NCPU=1                                                #Number of available CPU threads
 STARTSTEP=1                                           #Starting optimization step.
 MAXSTEPS=10                                           #Maximum optimization steps to be performed.
 DELETENC=T                                            #Delete .nc files after processing ("1" for True)
 GREPEVOLUTION=T                                       #Append band and maxgrad evolution ("1" for True)
-NAPTIME=10                                            #How long should the script sleep
-NAPUNITS=s                                            #In which units (h,s,m)
-RESTART=F                                             #In which units (h,s,m)
 STOPIFCONVERGED=F                                     #Stop the simulation if convergence is achieved.
 #-------------------------------------------------------------------------------------------------------------
 
 print_help() {
   echo
   echo "----------------------------------------------------------------------------------------------------------------------"
-  echo "                                                  FENEB WIZARD "
+  echo "                                                  FEOPT WIZARD "
   echo "----------------------------------------------------------------------------------------------------------------------"
   echo
-  echo "Welcome to Feneb Wizard, a tool designed to automate the running of Feneb calculations."
+  echo "Welcome to Feneb Wizard, a tool designed to automate the running of a Free Energy Optimizaion."
   echo
   echo "USAGE:"
-  echo "feneb_wizard [OPTIONS]"
+  echo "feopt_wizard [OPTIONS]"
   echo
   echo "OPTIONS:"
   echo "-s  Specify the path to sander [default: sander]"
   echo "-f  Specify the path to feneb [default: feneb]"
   echo "-m  Specify the sander input [default: prod.mdin]"
-  echo "-c  Specify the number of available CPU threads [default: 1]"
   echo "-x  Specify the starting optimization step [default: 1]"
   echo "-d  Specify the maximum optimization steps to be performed [default: 10]"
   echo "-g  Delete .nc files after processing (enter T for True) [default: T]"
-  echo "-a  Append band and maxgrad evolution (enter T for True) [default: T]"
-  echo "-u  Set sleep duration of the script [default: 10]"
-  echo "-v  Specify the units for sleep duration (s for seconds, m for minutes, d for days) [default: s]"
-  echo "-r  Resume a previous simulation (enter T for True) [default: F]"
+  echo "-a  Append maxgrad evolution (enter T for True) [default: T]"
   echo "----------------------------------------------------------------------------------------------------------------------"
   echo "NOTES:"
   echo "1. The following files must be provided in the 'inputs' folder:"
@@ -55,15 +45,11 @@ print_help() {
   echo "   taken from the previous one. This folder is automatically generated by this script, but for the first step (-x 1),"
   echo "   a 'STEP-0' folder must be manually generated."
   echo
-  echo "3. This script checks if all the MD runs have finished before executing the feneb code."
-  echo "   If they haven't, the script sleeps for a predefined time (as set by -u and -v) and checks again."
-  echo "   Typically, only a few minutes (or even seconds) are necessary."
-  echo
 }
 
 
 # Parse command line arguments
-while getopts "hs:f:m:c:i:x:d:g:a:u:r:" opt; do
+while getopts "hs:f:m:x:d:g:a:" opt; do
   case ${opt} in
     h ) print_help
         exit 0
@@ -73,13 +59,6 @@ while getopts "hs:f:m:c:i:x:d:g:a:u:r:" opt; do
     f ) FENEB=$OPTARG
       ;;
     m ) MDIN=$OPTARG
-      ;;
-    c ) NCPU=$OPTARG
-        if ! [[ "$NCPU" =~ ^[0-9]+$ ]]
-        then
-          echo "Error: -c option requires a numeric argument."
-          exit 1
-        fi
       ;;
     x ) STARTSTEP=$OPTARG
         if ! [[ "$STARTSTEP" =~ ^[0-9]+$ ]]
@@ -99,17 +78,6 @@ while getopts "hs:f:m:c:i:x:d:g:a:u:r:" opt; do
       ;;
     a ) GREPEVOLUTION=$OPTARG
       ;;
-    u ) NAPTIME=$OPTARG
-        if ! [[ "$NAPTIME" =~ ^[0-9]+$ ]]
-        then
-          echo "Error: -u option requires a numeric argument."
-          exit 1
-        fi
-      ;;
-    v ) UNITS=$OPTARG
-      ;;
-    r ) RESTART=$OPTARG
-      ;;
     * ) echo "Invalid option"
         exit 1
       ;;
@@ -127,33 +95,6 @@ is_num() {
 # Before doing anything, prints the print_help
 print_help
 
-# Check if the number of images is greater than 2
-is_num "$NIMAGES" "NIMAGES"
-if [ "$NIMAGES" -le 2 ]; then
-  if [ "$NIMAGES" -eq 1 ]; then
-    echo "NIMAGES=1 did you mean to perform a free energy optimization?"
-  else
-    echo "Error: NIMAGES must be greater than 2."
-    exit 1
-  fi
-fi
-
-# Check if NAPUNITS is either 's', 'm', or 'd'
-if ! echo "$NAPUNITS" | grep -E -q '^[smd]$'; then
-  echo "Error: NAPUNITS must be either 's', 'm', or 'd'."
-  exit 1
-fi
-
-# Check if NCPU is a number
-is_num "$NCPU" "NCPU"
-
-# Make sure NCPU is still a positive integer after any adjustments
-if [ "$NCPU" -le 0 ]; then
-  echo "Error: NCPU must be a positive integer."
-  exit 1
-fi
-
-
 # Check if inputs directory exists
 if [ ! -d "inputs" ]; then
     echo "Error: inputs directory not found."
@@ -169,30 +110,6 @@ for file in "${REQUIRED_FILES[@]}"; do
     fi
 done
 
-# Check if the extremes are fixed by inspecting the feneb.in file
-if  grep -s -q -F "rextrema" "inputs/feneb.in";
-then
-  REXTREMA=$(grep rextrema inputs/feneb.in|awk '{print $2}')
-  # Check if REXTREMA is T or F
-  REXTREMA=$(echo "${REXTREMA}" | tr -d '[:space:]')
-  if ! echo "${REXTREMA}" | grep -E -q '^[TF]$'; then
-    echo "Error: $REXTREMA must be either 'T' or 'F'."
-    exit 1
-  fi
-
-else
-  REXTREMA=F
-fi
-
-if [ "$REXTREMA" == "T" ]; then
-  REQUIRED_FILES=("feneb.extrema1" "feneb.extrema2")
-  for file in "${REQUIRED_FILES[@]}"; do
-    if [ ! -f "inputs/$file" ]; then
-        echo "Error: REXTREMA=T in feneb.in but required file $file not found in inputs directory."
-        exit 1
-    fi
-   done
-fi
 # Determine NIMAGES by inspecting the feneb.in file
 if  grep -s -q -F "nrep" "inputs/feneb.in";
 then
@@ -202,6 +119,13 @@ then
 else
   echo "Error: The number of images not found in feneb.in (nrep)"
   exit 1
+fi
+
+# Check if the number of images is equal to 1
+is_num "$NIMAGES" "NIMAGES"
+if [ "$NIMAGES" -ne 1 ]; then
+    echo "Error: NIMAGES must be 1 for aFree Energy optimization."
+    exit 1
 fi
 
 # Determine PREFIX by inspecting the feneb.in file
@@ -244,61 +168,15 @@ then
   STOPIFCONVERGED=$(grep stopifconverged inputs/feneb.in|awk '{print $2}')
 fi
 
-# Check NCPU against NIMAGES or NIMAGES-2 based on REXTREMA value
-if [ "$REXTREMA" == "T" ]; then
-  if [ "$NCPU" -gt "$(($NIMAGES - 2))" ]; then
-    echo "NCPU cannot be larger than NIMAGES-2 when REXTREMA=1. Setting NCPU to NIMAGES-2."
-    NCPU="$(($NIMAGES - 2))"
-  fi
-elif [ "$REXTREMA" == "F" ]; then
-  if [ "$NCPU" -gt "$NIMAGES" ]; then
-    echo "NCPU cannot be larger than NIMAGES when REXTREMA=0. Setting NCPU to NIMAGES."
-    NCPU="$NIMAGES"
-  fi
-fi
-
-#If M < N, then we need to split the MD runs in packages. A smarter option would be
-#to implement the FENEB code in the MPI version of sander, but I don't want to patch
-#the AMBER code.
-if [ $REXTREMA == "T" ] #If the extremes of the band are fixed
-then
-  NRUNS=$((NIMAGES-2))
-else
-  NRUNS=$((NIMAGES))
-fi
-#From now on we also need to know if the extremes are fixed or not
-if [ $REXTREMA == "T" ] #If the extremes of the band are fixed
-then
-  STARTREP=2
-  ENDREP=$((NIMAGES-1))
-else
-  STARTREP=1
-  ENDREP=$((NIMAGES))
-fi
-
-NPACKAGES=$((NRUNS/NCPU))
-NREMAINING=$((NRUNS-NPACKAGES*NCPU))
-OLDSTARTREP=$((STARTREP)) #Only necessary for restart option
-OLDNRUNS=$((NRUNS)) #Only necessary for restart option
-
 
 echo "----------------------------------------------------------------------------------------------------------------------"
-echo "                                          STARTING THE FENEB SIMULATION"
+echo "                                          STARTING THE FEOPT SIMULATION"
 echo "----------------------------------------------------------------------------------------------------------------------"
 echo " "
-echo "The simulation will be parallelized according to the required number of"
-echo "MD simulations to be performed and the number of cpu threads available."
+echo "The restraint reference will be updated after each MD simulation"
 echo " "
-if [ $NREMAINING == '0' ]; then
-  echo  "The $NRUNS  MD simulations will be run in $NPACKAGES packages of $NCPU each."
-else
-  echo  "The $NRUNS  MD simulations will be run in $NPACKAGES packages of $NCPU each"
-  echo  "and an extra one with $NREMAINING simulations"
-fi
-#Note NPACKAGES is rounded down. For example, if M=8 and NRUNS=23 (25 images with fixed extremes),
-#NPACKAGES will be equal to 2. So, after running 2*8=16 MD runs, we still need to run the remaining
-#NRUNS-(NPACKAGES*M) runs.
 
+k=1 #The extreme is called PREFIX_1
 for ((step=STARTSTEP; step<=MAXSTEPS; step++)); # Optimization loop
 do
         echo "----------------"
@@ -315,123 +193,15 @@ do
         PREVSTEP=$((step-1|bc))
         if [ $step == "1" ] #If this is the first optimization step, copy _r_ files to _f_
           then
-          for ((k=STARTREP; k<=ENDREP; k++));
-          do
             cp ../STEP-${PREVSTEP}/${NAME}_r_${k}.rst7 .
             cp ${NAME}_r_${k}.rst7 ${NAME}_fprev_${k}.rst7
-          done
         else #copy _f_ files from previous step and call them _fprev_
-          for ((k=STARTREP; k<=ENDREP; k++));
-          do
             cp ../STEP-${PREVSTEP}/${NAME}_o_${k}.rst7 ${NAME}_r_${k}.rst7
             cp ../STEP-${PREVSTEP}/${NAME}_f_${k}.rst7 ${NAME}_fprev_${k}.rst7
-          done
         fi
 
         echo "Running MD"
 
-        if [ $RESTART = 'T' ]; then
-          if [ $step -eq $STARTSTEP ]; then
-            echo "Trying to restart from incomplete simulation..."
-            echo "Searching files..."
-            seq_finished=T
-            last_finished=$((STARTREP))
-            l=$((STARTREP))
-            while [ "$seq_finished" = "T" -a $l -le $ENDREP ];
-            do
-            if  grep -s -q -F "wallclock()" "${NAME}_${l}.out"; then
-              seq_finished=T
-              last_finished=$((l))
-            else
-              seq_finished=F
-            fi
-            l=$((l+1))
-            done
-            if [ $last_finished -ge $STARTREP ]; then
-            echo "Images from $STARTREP to $l have finished"
-            echo "Only the remaining $((NRUNS-last_finished)) will be run during this first step"
-            NRUNS=$((NRUNS-last_finished))
-            STARTREP=$((last_finished+1))
-            NPACKAGES=$((NRUNS/NCPU))
-            NREMAINING=$((NRUNS-NPACKAGES*NCPU))
-            echo "Only for this step, the remaining $((NRUNS)) will be run during this first step"
-            if [ $NREMAINING == '0' ]; then
-              echo  "The $((NRUNS))  MD simulations will be run in $NPACKAGES packages of $NCPU each."
-            else
-              echo  "The $((NRUNS))  MD simulations will be run in $NPACKAGES packages of $NCPU each"
-              echo  "and an extra one with $NREMAINING simulations"
-            fi
-            fi
-          else
-            STARTREP=$((OLDSTARTREP))
-            NRUNS=$((OLDNRUNS))
-            NPACKAGES=$((NRUNS/NCPU))
-            NREMAINING=$((NRUNS-NPACKAGES*NCPU))
-          fi
-        fi
-
-        FROM=$((STARTREP))
-	      UPTO=$((FROM+NCPU-1))
-        for ((i=1; i<=NPACKAGES; i++)); # Start running each PACKAGE of M MD simulations
-        do
-          echo "Running package $i (range from $FROM to $UPTO)"
-          for ((k=FROM;k<UPTO;k++)); # Start running M-1 MD
-          do
-            $SANDER -O -i prod.mdin \
-                       -o ${NAME}_${k}.out \
-                       -p $TOPOLOGY \
-                       -c ${NAME}_fprev_${k}.rst7 \
-                       -r ${NAME}_f_${k}.rst7 \
-                       -x ${NAME}_f_${k}.nc \
-                       -ref ${NAME}_r_${k}.rst7 &
-          done
-	       #Run the last MD (of this package), and waits until its finished
-          $SANDER -O -i prod.mdin \
-                  -o ${NAME}_${k}.out \
-                  -p $TOPOLOGY \
-                  -c ${NAME}_fprev_${k}.rst7 \
-                  -r ${NAME}_f_${k}.rst7 \
-                  -x ${NAME}_f_${k}.nc \
-	          -ref ${NAME}_r_${k}.rst7
-          #Checks that all Images of this package have finished
-          count=0
-          while [ $count -lt $NCPU ];
-          do
-            count=0
-            for ((l=FROM; l<=UPTO; l++));
-            do
-              if  grep -s -q -F "wallclock()" "${NAME}_${l}.out";
-              then
-                count=$((count+1))
-              else
-                echo "image number $l has not finished"
-              fi
-            done
-            if [ "$count" == "$NCPU" ]
-            then
-              echo "all Images of package $i have finished"
-            else
-              echo "taking a" $NAPTIME $NAPUNITS " long nap..."
-              sleep $NAPTIME$NAPUNITS
-            fi
-          done
-          FROM=$((k+1))
-          UPTO=$((FROM+NCPU-1))
-        done #packages
-	      #Runs remaining MD simulations (if any)
-        if [ $NREMAINING != '0' ]; then
-        UPTO=$((ENDREP))
-        for ((k=FROM; k<UPTO; k++)); # Starts in k+1 image, according to last FROM update
-        do
-          $SANDER -O -i prod.mdin \
-                     -o ${NAME}_${k}.out \
-                     -p $TOPOLOGY \
-                     -c ${NAME}_fprev_${k}.rst7 \
-                     -r ${NAME}_f_${k}.rst7 \
-                     -x ${NAME}_f_${k}.nc \
-                     -ref ${NAME}_r_${k}.rst7 &
-        done
-        #Run the last remaining MD, and waits until its finished
         $SANDER -O -i prod.mdin \
                    -o ${NAME}_${k}.out \
                    -p $TOPOLOGY \
@@ -439,31 +209,8 @@ do
                    -r ${NAME}_f_${k}.rst7 \
                    -x ${NAME}_f_${k}.nc \
                    -ref ${NAME}_r_${k}.rst7
-	      #Checks that all remaining Images have finished
-        count=0
-        while [ $count -lt $NREMAINING ];
-        do
-          count=0
-          for ((l=FROM; l<=UPTO; l++));
-          do
-          if  grep -s -q -F "wallclock()" "${NAME}_${l}.out";
-          then
-            count=$((count+1))
-          else
-            echo "image number $l has not finished"
-          fi
-          done
-          if [ $count == $NREMAINING ]
-          then
-            echo "all remaining Images have finished"
-          else
-            echo "taking a" $NAPTIME $UNITS " long nap..."
-            sleep $NAPTIME$UNITS
-          fi
-        done
-        fi
-	#Run feneb
-        echo "Running feneb optimization"
+
+        echo "Running Free Energy optimization"
         $FENEB
 
 	if [ $DELETENC == "T" ] #Delete .nc files
@@ -473,12 +220,9 @@ do
 
   if [ $GREPEVOLUTION == "T" ] #Copy optimization information to .dat files
   then
-    GRADPERP=$(grep "Band max force:" feneb.out|awk '{print $4}')
-    cat profile.dat >> ../bandevolution.dat
-    echo " " >> ../bandevolution.dat
-    echo $step $GRADPERP >> ../maxgradevolution.dat
+    GRAD=$(grep "Max force:" feneb.out|awk '{print $3}')
+    echo $step $GRAD >> ../maxgradevolution.dat
   fi
-
 
   if [ $STOPIFCONVERGED == "T" ] # Check convergence if required by STOPIFCONVERGED
   then
@@ -487,7 +231,7 @@ do
       echo "Convergence achieved: Stoping simulation..."
       echo "----------------------------------------------------------------------------------------------------------------------"
       echo "                                             HAPPY LANDING"
-      echo "                                       FENEB OPTIMIZATION CONVERGED"
+      echo "                                       FEOPT OPTIMIZATION CONVERGED"
       echo "----------------------------------------------------------------------------------------------------------------------"
       exit 1
     fi
